# Generated by Django 6.0.5 on 2026-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash — Paid Immediately'), ('credit', 'Credit — Pay Later')], default='cash', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='suppliers.supplierdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retailer_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplierdelivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.suppliercreditaccount')),
            ],
        ),
    ]
