# Generated by Django 6.0.5 on 2026-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('bar', 'Bar'), ('kg', 'Kilogram'), ('piece', 'Piece'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('bundle', 'Bundle')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retailer_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('is_deposit_eligible', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.category')),
            ],
        ),
    ]
