# Generated by Django 6.0.5 on 2026-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='deposits.depositcustomer')),
                ('product', models.ForeignKey(limit_choices_to={'is_deposit_eligible': True}, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_picked', models.PositiveIntegerField()),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('served_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='deposits.depositrecord')),
            ],
        ),
    ]
