# Generated by Django 6.0.5 on 2026-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='target_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
