# Generated by Django 6.0.5 on 2026-05-21 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('all', 'All Staff'), ('admin', 'Accounts / Admin'), ('store_manager', 'Store Manager'), ('sales_attendant', 'Sales Attendant')], default='all', help_text='Used when recipient is blank', max_length=20)),
                ('category', models.CharField(choices=[('low_stock', 'Low Stock'), ('overdue_credit', 'Overdue Supplier Credit'), ('deposit_ready', 'Deposit Ready for Pickup'), ('new_sale', 'New Sale'), ('new_delivery', 'New Delivery'), ('credit_payment', 'Credit Payment Made'), ('new_deposit', 'New Deposit')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank to target by role instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
